name: nn_traffic_flow_prediction
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py311h582051c_0
  - aiohttp-cors=0.8.1=pyhd8ed1ab_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alembic=1.17.2=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - autograd=1.8.0=pyhd8ed1ab_0
  - aws-c-auth=0.9.1=hc6331ae_3
  - aws-c-cal=0.9.2=hef2a5b8_1
  - aws-c-common=0.12.4=hfd05255_0
  - aws-c-compression=0.3.1=ha8a2810_6
  - aws-c-event-stream=0.5.6=h9e52e59_3
  - aws-c-http=0.10.4=hffefcd8_3
  - aws-c-io=0.22.0=h20b9e97_1
  - aws-c-mqtt=0.13.3=he28f3f4_6
  - aws-c-s3=0.8.6=ha4cb493_5
  - aws-c-sdkutils=0.2.4=ha8a2810_1
  - aws-checksums=0.2.7=ha8a2810_2
  - aws-crt-cpp=0.34.4=hc2cf59f_0
  - aws-sdk-cpp=1.11.606=h296c955_4
  - bokeh=3.8.0=pyhd8ed1ab_0
  - brotli=1.1.0=hfd05255_4
  - brotli-bin=1.1.0=hfd05255_4
  - brotli-python=1.1.0=py311h3e6a449_4
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.11.12=h4c7d964_0
  - cachetools=6.2.2=pyhd8ed1ab_0
  - cairo=1.18.4=h5782bbf_0
  - catboost=1.2.7=py311h5360e5d_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311h3485c13_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - clarabel=0.11.1=py311h2b762b8_1
  - click=8.3.0=pyh7428d3b_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorful=0.5.8=pyhd8ed1ab_0
  - colorlog=6.10.1=pyh7428d3b_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h3fd045d_2
  - coreforecast=0.0.16=py311h3fd045d_1
  - cpython=3.11.13=py311hd8ed1ab_0
  - cryptography=46.0.3=py311h5e0b3ae_0
  - cvxpy=1.7.2=py311h1ea47a8_0
  - cvxpy-base=1.7.2=py311h11fd7f3_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.1.0=py311h3485c13_1
  - dask=2025.10.0=pyhcf101f3_0
  - dask-core=2025.10.0=pyhcf101f3_0
  - dask-glm=0.3.2=pyhd8ed1ab_0
  - dask-ml=2025.1.0=pyhd8ed1ab_0
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_0
  - distlib=0.4.0=pyhd8ed1ab_0
  - distributed=2025.10.0=pyhcf101f3_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py311h3f79411_0
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - frozenlist=1.7.0=py311hdf60d3a_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - getopt-win32=0.1=h6a83c73_3
  - google-api-core=2.28.1=pyhd8ed1ab_0
  - google-auth=2.43.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - graphite2=1.3.14=hac47afa_2
  - graphviz=13.1.2=ha5e8f4b_0
  - greenlet=3.2.4=py311h3e6a449_1
  - grpcio=1.73.1=py311h989a076_1
  - gts=0.7.6=h6b5321d_4
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=11.4.5=h5f2951f_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.6.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.9=py311h275cad7_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=22.0.0=h2031902_0_cpu
  - libarrow-acero=22.0.0=h7d8d6a5_0_cpu
  - libarrow-compute=22.0.0=h2db994a_0_cpu
  - libarrow-dataset=22.0.0=h7d8d6a5_0_cpu
  - libarrow-substrait=22.0.0=hf865cc0_0_cpu
  - libblas=3.9.0=35_h5709861_mkl
  - libboost=1.88.0=h3d2b97d_0
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.16.0=h43ecb02_0
  - libdeflate=1.22=h2466b09_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libgd=2.3.3=h7208af6_11
  - libglib=2.84.4=hfaec014_0
  - libgomp=15.2.0=h1383e82_7
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblightgbm=4.6.0=cpu_h5d2ca61_6
  - libosqp=1.0.0=np2py312h325a191_2
  - libparquet=22.0.0=h7051d1f_0_cpu
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_2
  - libqdldl=0.1.8=he0c23c2_1
  - libre2-11=2025.08.12=h0eb2380_1
  - libsodium=1.0.20=hc70643c_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.0=hfc51747_1
  - libtorch=2.8.0=cpu_mkl_hffd3a6c_101
  - libutf8proc=2.11.0=h0b34c2f_0
  - libuv=1.51.0=hfd05255_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxgboost=3.1.1=cpu_hd161407_0
  - libxml2=2.13.8=h741aa76_1
  - libzlib=1.3.1=h02ab6af_0
  - lightgbm=4.6.0=cpu_py_6
  - lightning=2.5.6=pyhd8ed1ab_0
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - llvm-openmp=20.1.8=h29ce207_0
  - llvmlite=0.45.1=py311h4f568be_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.4=py311h6118f10_1
  - lz4-c=1.10.0=h2466b09_1
  - mako=1.3.10=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib-base=3.10.7=py311h1675fdf_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2024.2.2=h57928b3_16
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py311h3fd045d_0
  - multidict=6.6.3=py311h3f79411_0
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.10.0=pyhcf101f3_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6=pyhcf101f3_0
  - neuralforecast=3.1.2=pyhd8ed1ab_0
  - numba=0.62.1=py311hffedbe7_0
  - numpy=1.26.4=py311h0b4df5a_0
  - opencensus=0.11.3=pyhd8ed1ab_1
  - opencensus-context=0.1.3=py311h1ea47a8_4
  - opencl-headers=2025.06.13=he0c23c2_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.0=h725018a_0
  - optree=0.18.0=py311h3fd045d_0
  - optuna=4.6.0=pyhd8ed1ab_0
  - orc=2.2.1=h7414dfc_0
  - osqp=1.0.5=np2py311hf2e69b3_2
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h11fd7f3_1
  - pango=1.56.4=h03d888a_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h3402e2f_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py311h26a3c52_3
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.4.0=pyhd8ed1ab_0
  - polars=1.35.0=pyh6a1acc5_0
  - polars-default=1.33.1=py310h0d56bed_1
  - polars-runtime-32=1.35.0=py310hca7251b_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py311h5082efb_0
  - proto-plus=1.26.1=pyhd8ed1ab_0
  - protobuf=6.31.1=py311heca59f8_2
  - psutil=7.1.2=py311hf893f09_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-spy=0.4.1=h77a83cd_0
  - py-xgboost=3.1.1=cpu_pyh24504c9_0
  - pyarrow=22.0.0=py311h1ea47a8_0
  - pyarrow-core=22.0.0=py311ha836b3b_0_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh6a1d191_3
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py311hf51aa87_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.9=he1021f5_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.11.13=hd8ed1ab_0
  - python-graphviz=0.21=pyhbacfb6d_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py311h2f2c37c_1
  - python_abi=3.11=2_cp311
  - pytorch=2.8.0=cpu_mkl_py311_h4f6e1b8_101
  - pytorch-forecasting=1.5.0=pyh865f8e1_0
  - pytorch-lightning=2.5.5=pyh2a12c56_0
  - pytorch_geometric=2.7.0=pyhc455866_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pywin32=311=py311hefeebc8_1
  - pyyaml=6.0.3=py311h3f79411_0
  - pyzmq=27.1.0=py311hb77b9c8_0
  - qdldl-python=0.1.7.post5=np2py311hf2e69b3_3
  - qhull=2020.2=hc790b64_5
  - ray-core=2.46.0=py311h5da7b33_0
  - ray-default=2.46.0=py311haa95532_0
  - ray-tune=2.46.0=py311haa95532_0
  - re2=2025.08.12=ha104f34_1
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rpds-py=0.29.0=py311hf51aa87_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - ruff=0.14.5=h15e3a1f_0
  - scikit-learn=1.6.1=py311hdcb8d17_0
  - scikit-lego=0.9.1=pyhd8ed1ab_0
  - scipy=1.16.2=py311h9a1c30b_0
  - scs=3.2.9=default_py311hd5dc5f8_1
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setproctitle=1.2.2=py311h827c3e9_2
  - setuptools=78.1.1=py311haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=h67fd636_0
  - smart_open=7.5.0=pyhcf101f3_0
  - snappy=1.2.2=h7fa0ca8_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sparse=0.17.0=pyhcf101f3_0
  - sqlalchemy=2.0.44=py311h3485c13_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py311h17033d2_1
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2021.13.0=h18a62a1_3
  - tblib=3.1.0=pyhd8ed1ab_0
  - tensorboardx=2.6.2.2=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - tomli=2.3.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - tornado=6.5.2=py311h3485c13_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - umap-learn=0.5.9.post2=py311h1ea47a8_0
  - unicodedata2=17.0.0=py311h3485c13_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utilsforecast=0.2.14=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - virtualenv=20.35.4=pyhd8ed1ab_0
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=1.17.3=py311h3485c13_1
  - xorg-libice=1.1.2=h0e40799_0
  - xorg-libsm=1.2.6=h0e40799_0
  - xorg-libx11=1.8.12=hf48077a_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xorg-libxext=1.3.6=h0e40799_0
  - xorg-libxpm=3.5.17=h0e40799_1
  - xorg-libxt=1.3.1=h0e40799_0
  - xxhash=0.8.3=hbba6f48_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.22.0=py311h3f79411_0
  - yellowbrick=1.5=pyhd8ed1ab_1
  - zeromq=4.3.5=h5bddc39_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.25.0=py311hf893f09_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - clean-text==0.6.0
      - emoji==1.7.0
      - ftfy==6.3.1
      - intel-openmp
      - holidays
      - astral
      - optuna-integration[pytorch_lightning]
