name: nn_traffic
channels:
  - pytorch
  - conda-forge
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # --- Python ---
  - python=3.11.9

  # --- ML ---
  - scikit-learn=1.6.1
  - scikit-lego=0.9.1

  # --- PyTorch ---
  - pytorch=2.8.0
  - pytorch-lightning
  - pytorch-forecasting
  - pytorch-cuda=12.1
  - cudnn
  - optuna

  # --- Scientific stack ---
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn

  # --- Utilities ---
  - pip
  - ipykernel
  - jupyterlab
  - tqdm
  - pyyaml

  # --- Other ---
  - pydantic

  # --- pip packages ---
  - pip:
      - intel-openmp
      - clean-text
      - emoji
      - ftfy
      - holidays
      - astral
